# coding: utf-8
lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require_relative 'lib/jekyll-bluesky/version'

Gem::Specification.new do |s|
  s.name = 'jekyll-bluesky'
  s.version = Jekyll::Bluesky::VERSION
  s.license = 'MIT'
  s.summary = 'This Jekyll plugin displays Bluesky tweets on the site, enabling automatic and customizable integration of posts without relying on external dynamic solutions.'
  s.description = 'This Jekyll plugin allows displaying Bluesky tweets directly on a static site. It fetches posts from the decentralized social network Bluesky and incorporates them into the content generated by Jekyll, making it easier to integrate real-time updates without the need for complex external APIs.'
  s.authors = ['Felipe Dias']
  s.email = 'felipe@dias.dev.br'
  s.homepage = 'https://github.com/fdoliv/jekyll-bluesky'

  s.files = Dir['lib/**/*.rb'] # Inclui apenas arquivos Ruby
  s.require_paths = ['lib'] # Define o caminho para os arquivos principais

  s.required_ruby_version = '>= 3.0.0'

  s.add_dependency 'jekyll', '~> 3.9.0'
  s.add_dependency "http", "~> 5.0"
end